baseURL = 'https://wiki.smallkirby.xyz'
languageCode = 'jp'
title = 'WIKIRBY'

disqusShortname = 'https-wiki-smallkirby-xyz'
gcs_engine_id = '74c8139ea6716476d'
sidebar_search_disable = false

github_repo = 'https://github.com/smallkirby/wikirby'

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[outputs]
section = ["HTML", "RSS"]
