baseURL = 'https://wiki.smallkirby.xyz'
languageCode = 'jp'
title = 'WIKIRBY'

disqusShortname = 'https-wiki-smallkirby-xyz'

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
